board_size: 10  # Taille du plateau (10x10)
speed: 10        # Vitesse en cases par seconde
display: true   # Active ou désactive l'affichage graphique
victory_condition: 35 # nombre de case de la taille du serpent pour definir la victoire
mode: model  # Peut être "player" ou "model" ou train
step_by_step: false
rewards:
  green_apple: 50
  red_apple: -45
  move_without_eating: -1
  collision: -100
training:
  sessions: 10000
model:
  name: "model_lenght.pkl"